server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<mysql_ip>:3306/db_account?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 12345678

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: ralph.devops.entities
