server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: <nacos_ip>:<nacos_port> #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
