server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.24.221.135:3306/db_account?useUnicode=true&characterEncoding-utr-8&useSSL=false
#    username: root
#    password: 12345678
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.120.217:3306/mp?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: oppo_tools



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: ralph.devops.entities

#set eureka client environment
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
#      defaultZone: http://localhost:7001/eureka
      # 集群的修改配置
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
