server:
  port: 8089
#表单上传文件的大小
spring:
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "100MB"

  datasource:
    url: "jdbc:mysql://120.24.221.135:3306/db_account"
    username: "root"
    password: "12345678"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    druid:
      #监控SpringBean
      aop-patterns: "ralph.ci.springboot"
      # 底层开启功能，stat（sql监控），wall（防火墙）
      filters: "stat,wall"

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      #监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  jdbc:
    template:
      query-timeout: "10"