server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: default
    nacos:
      discovery:
        server-addr: <nacos_ip>:<nacos_port>
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://<mysql_ip>:3306/seata_order
    username: root
    password: <mysql_password>

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
